In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv("data_final.csv")

In [3]:
df

name                                              value  \
0      _ga_LCREYHZKHN              GS1.2.1703155633.1.1.1703155634.0.0.0   
1                _gid                        GA1.2.1609768839.1703155633   
2                _gat                                                  1   
3                 _ga                        GA1.2.1594730030.1703155633   
4      _ga_W9X1GB1SVR             GS1.1.1703196321.1.1.1703196330.51.0.0   
...               ...                                                ...   
65290           _pxhd  7Zrw5YsFMOR5AfFuY/lqLzs5NsYkDEOIVH3ziwYGhUbaxZ...   
65291             wfu  MTcwMzA4NjgyMHx4dFFsNHJpcDh5QloydzRsTDhfMThHVG...   
65292             moo  Ild0K2M1KysrKzFRZVdMQW5PVW8rR2c9PSI%3D--2ca10f...   
65293   _zurb_session  ejdvRjVoUExmWjkrK0ZNZ0pITjMvNVpRSlAvZWh0Rm10eE...   
65294        moocrypt  ImV5SnBkaUk2SWtkSlNHbDFMMlJJUkV4WlFYZzFTVTFHU2...   

                   domain path       expires  size  httpOnly  secure  session  \
0      .100datingsite.com    /  1.737716e+09    51     False   False    False   
1      .100datingsite.com    /  1.703242e+09    31     False   False    False   
2      .100datingsite.com    /  1.703156e+09     5     False   False    False   
3      .100datingsite.com    /  1.737716e+09    30     False   False    False   
4             .104.com.tw    /  1.737756e+09    52     False   False    False   
...                   ...  ...           ...   ...       ...     ...      ...   
65290           zazzle.nl    /  1.733924e+09   202     False    True    False   
65291      zenwriting.net    /  1.718639e+09   127      True    True    False   
65292            zurb.com    /  1.737715e+09    83     False   False    False   
65293            zurb.com    / -1.000000e+00   319      True   False     True   
65294            zurb.com    / -1.000000e+00   184     False   False     True   

       sameParty sourceScheme  sourcePort  \
0          False       Secure         443   
1          False       Secure         443   
2          False       Secure         443   
3          False       Secure         443   
4          False       Secure         443   
...          ...          ...         ...   
65290      False       Secure         443   
65291      False       Secure         443   
65292      False       Secure         443   
65293      False       Secure         443   
65294      False       Secure         443   

                                                    desc      category  \
0                                                Unknown       Unknown   
1                                                   _gid   Performance   
2      This cookie name is associated with Google Uni...   Performance   
3      This cookie name is associated with Google Uni...   Performance   
4      There is not yet any general information about...       Unknown   
...                                                  ...           ...   
65290  There is not yet any general information about...       Unknown   
65291                                            Unknown       Unknown   
65292  There is not yet any general information about...       Unknown   
65293                                            Unknown       Unknown   
65294                                            Unknown       Unknown   

      sameSite  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
...        ...  
65290      NaN  
65291      NaN  
65292      NaN  
65293      NaN  
65294      NaN  

[65295 rows x 15 columns]

In [4]:
len(df.name[df.category!=" Unknown"])

32387

In [5]:
(df['category'] == " Unknown").sum()

32908

In [6]:
len(df.category)

65295

In [7]:
df.category.unique()

array([' Unknown', ' Performance', ' Targeting/Advertising',
       ' Strictly Necessary', ' Functionality'], dtype=object)

In [8]:
len(df)

65295

In [9]:
len(df[df.category == " Unknown"]) + len(df.name[df.category!=" Unknown"])

65295

In [10]:
df_known_cat = df[df.category != " Unknown"]

In [11]:
df_known_cat.head()

name                                              value  \
1   _gid                        GA1.2.1609768839.1703155633   
2   _gat                                                  1   
3    _ga                        GA1.2.1594730030.1703155633   
5   _fbp                      fb.2.1703196323660.2058557705   
6  _clsk  166tg7v%7C1703196323932%7C1%7C0%7Cq.clarity.ms...   

               domain path       expires  size  httpOnly  secure  session  \
1  .100datingsite.com    /  1.703242e+09    31     False   False    False   
2  .100datingsite.com    /  1.703156e+09     5     False   False    False   
3  .100datingsite.com    /  1.737716e+09    30     False   False    False   
5         .104.com.tw    /  1.710972e+09    33     False   False    False   
6         .104.com.tw    /  1.703283e+09    61     False   False    False   

   sameParty sourceScheme  sourcePort  \
1      False       Secure         443   
2      False       Secure         443   
3      False       Secure         443   
5      False       Secure         443   
6      False       Secure         443   

                                                desc                category  \
1                                               _gid             Performance   
2  This cookie name is associated with Google Uni...             Performance   
3  This cookie name is associated with Google Uni...             Performance   
5  Used by Facebook to deliver a series of advert...   Targeting/Advertising   
6  Used by Microsoft Clarity to connect multiple ...             Performance   

  sameSite  
1      NaN  
2      NaN  
3      NaN  
5      Lax  
6      NaN

In [12]:
df_known_cat.category.unique()

array([' Performance', ' Targeting/Advertising', ' Strictly Necessary',
       ' Functionality'], dtype=object)

In [13]:
df_known_cat.category.apply(lambda x : len(x))

1        12
2        12
3        12
5        22
6        12
         ..
65262    19
65273    19
65282    19
65286    19
65288    19
Name: category, Length: 32387, dtype: int64

In [14]:
import pandas as pd

# Assuming df_known_cat is your DataFrame
df_known_cat.loc[:, 'category'] = df_known_cat['category'].str.strip()

In [15]:
df_known_cat.category.unique()

array(['Performance', 'Targeting/Advertising', 'Strictly Necessary',
       'Functionality'], dtype=object)

In [16]:
df_known_cat.name

1             _gid
2             _gat
3              _ga
5             _fbp
6            _clsk
           ...    
65262    PHPSESSID
65273        crumb
65282    csrftoken
65286    NSC_xxx01
65288    NSC_xxx03
Name: name, Length: 32387, dtype: object

In [17]:
len(df_known_cat.name.unique())

4634

In [18]:
len(df_known_cat.domain.unique())

6898

In [19]:
len(df_known_cat.desc.unique())

406

In [20]:
df_known_cat.sourcePort.unique()

array([443,  80], dtype=int64)

In [21]:
df_known_cat.sourceScheme.unique()

array(['Secure', 'NonSecure'], dtype=object)

In [22]:
df_known_cat.sameParty.unique()

array([False])

In [23]:
df_known_cat.session.unique()

array([False,  True])

In [24]:
df_known_cat.secure.unique()

array([False,  True])

In [25]:
df_known_cat.httpOnly.unique()

array([False,  True])

In [26]:
df_known_cat.path.unique()

array(['/', '/de/de', '/learn/cookie-policy', '/chrome', '/de-de',
       '/nl/publieksportaal', '/en', '/privacy', '/int/', '/de', '/de/',
       '/legal', '/en-us/legal', '/carrier', '/s', '/Pages',
       '/info/legal', '/about-us/policies', '/home/', '/main', '/pages'],
      dtype=object)

In [27]:
len(df_known_cat.expires.unique())

24222

In [28]:
df_known_cat.desc.value_counts()

desc
This cookie name is associated with Google Universal Analytics - which is a significant update to Google's more commonly used analytics service. This cookie is used to distinguish unique users by assigning a randomly generated number as a client identifier. It is included in each page request in a site and used to calculate visitor, session and campaign data for the sites analytics reports.  By default it is set to expire after 2 years, although this is customisable by website owners.                                              3908
_gid                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

In [29]:
df_known_cat.drop(columns = ["sourcePort", "sourceScheme", "sameParty"], axis = 1)

name                                              value  \
1           _gid                        GA1.2.1609768839.1703155633   
2           _gat                                                  1   
3            _ga                        GA1.2.1594730030.1703155633   
5           _fbp                      fb.2.1703196323660.2058557705   
6          _clsk  166tg7v%7C1703196323932%7C1%7C0%7Cq.clarity.ms...   
...          ...                                                ...   
65262  PHPSESSID                         sp3k29c3p4eft35idg07i1r9bu   
65273      crumb  BdMirHLoDS89YzAzNjU4ODM3ZGVlNTBiNjVmMjFjMjY2ZD...   
65282  csrftoken  LgSLVd0eOXMJYYUCLOCRkPkZbPXPD9gSu5yMz7x7rZwC8I...   
65286  NSC_xxx01  4819a3deaedfe3205f0c2d3f4548c2478ecfe73d8d9287...   
65288  NSC_xxx03  7ce2a3d959dcb0dc573648361b1877ded04cb3a914b5e5...   

                   domain path       expires  size  httpOnly  secure  session  \
1      .100datingsite.com    /  1.703242e+09    31     False   False    False   
2      .100datingsite.com    /  1.703156e+09     5     False   False    False   
3      .100datingsite.com    /  1.737716e+09    30     False   False    False   
5             .104.com.tw    /  1.710972e+09    33     False   False    False   
6             .104.com.tw    /  1.703283e+09    61     False   False    False   
...                   ...  ...           ...   ...       ...     ...      ...   
65262         www5.usp.br    / -1.000000e+00    35     False   False     True   
65273    youradchoices.ca    / -1.000000e+00    57     False    True     True   
65282          zapier.com    /  1.734504e+09    73     False    True    False   
65286          zazzle.com    / -1.000000e+00    81      True    True     True   
65288           zazzle.nl    / -1.000000e+00    81      True    True     True   

                                                    desc  \
1                                                   _gid   
2      This cookie name is associated with Google Uni...   
3      This cookie name is associated with Google Uni...   
5      Used by Facebook to deliver a series of advert...   
6      Used by Microsoft Clarity to connect multiple ...   
...                                                  ...   
65262  PHP session cookie associated with embedded co...   
65273  This cookie is associated with SquareSpace.  I...   
65282  This cookie is associated with the Django web ...   
65286  This cookie name is associated with the Netsca...   
65288  This cookie name is associated with the Netsca...   

                    category sameSite  
1                Performance      NaN  
2                Performance      NaN  
3                Performance      NaN  
5      Targeting/Advertising      Lax  
6                Performance      NaN  
...                      ...      ...  
65262     Strictly Necessary      NaN  
65273     Strictly Necessary      NaN  
65282     Strictly Necessary      NaN  
65286     Strictly Necessary      NaN  
65288     Strictly Necessary      NaN  

[32387 rows x 12 columns]

In [30]:
df = df_known_cat.copy() # the df contains only the rows with known category

In [31]:
df.head()

name                                              value  \
1   _gid                        GA1.2.1609768839.1703155633   
2   _gat                                                  1   
3    _ga                        GA1.2.1594730030.1703155633   
5   _fbp                      fb.2.1703196323660.2058557705   
6  _clsk  166tg7v%7C1703196323932%7C1%7C0%7Cq.clarity.ms...   

               domain path       expires  size  httpOnly  secure  session  \
1  .100datingsite.com    /  1.703242e+09    31     False   False    False   
2  .100datingsite.com    /  1.703156e+09     5     False   False    False   
3  .100datingsite.com    /  1.737716e+09    30     False   False    False   
5         .104.com.tw    /  1.710972e+09    33     False   False    False   
6         .104.com.tw    /  1.703283e+09    61     False   False    False   

   sameParty sourceScheme  sourcePort  \
1      False       Secure         443   
2      False       Secure         443   
3      False       Secure         443   
5      False       Secure         443   
6      False       Secure         443   

                                                desc               category  \
1                                               _gid            Performance   
2  This cookie name is associated with Google Uni...            Performance   
3  This cookie name is associated with Google Uni...            Performance   
5  Used by Facebook to deliver a series of advert...  Targeting/Advertising   
6  Used by Microsoft Clarity to connect multiple ...            Performance   

  sameSite  
1      NaN  
2      NaN  
3      NaN  
5      Lax  
6      NaN

In [32]:
df.drop("sameSite", axis = 1, inplace = True)

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

text_cols = ['name', 'value', 'desc','domain']

# Use TfidfVectorizer for text columns
text_transformer = TfidfVectorizer()

# Apply the transformer to text columns
text_features = text_transformer.fit_transform(df[text_cols])

# Display the transformed text features
print(len(text_features.toarray()))

4


In [34]:
from sklearn.preprocessing import OneHotEncoder

category_cols = ['category']

# Use OneHotEncoder for category column
category_transformer = OneHotEncoder()

# Apply the transformer to the category column
category_features = category_transformer.fit_transform(df[category_cols])

# Display the transformed category features
print(len(category_features.toarray()))

32387


In [35]:
from sklearn.preprocessing import StandardScaler

numeric_cols = ['size', 'expires']

# Use StandardScaler for numeric columns
numeric_transformer = StandardScaler()

# Apply the transformer to numeric columns
numeric_features = numeric_transformer.fit_transform(df[numeric_cols])

# Display the transformed numeric features
print(len(numeric_features))


32387


In [36]:
bool_cols = ['httpOnly', 'secure', 'session']
df[bool_cols] = df[bool_cols].apply(lambda x: x.apply(lambda y: 1 if y else 0))

In [37]:
df.head()
df["category"].unique()

array(['Performance', 'Targeting/Advertising', 'Strictly Necessary',
       'Functionality'], dtype=object)

In [38]:
X = df.drop("category", axis = 1)
y = df.category

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np


# Separate columns for transformation and remaining columns
# text_cols = ['name', 'value', 'desc']
numeric_cols = ['size', 'expires']
bool_cols = ['httpOnly', 'secure', 'session']

# Define transformers
text_transformer = TfidfVectorizer()
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),  # Handle missing values if any
    ('scaler', StandardScaler())
])
bool_transformer = 'passthrough'  # No transformation needed for boolean columns

# Apply transformers to the specified columns
preprocessor = ColumnTransformer(
    transformers=[
#         ('text', text_transformer, text_cols),
#         ('category', category_transformer, category_cols),
        ('numeric', numeric_transformer, numeric_cols),
        ('bool', bool_transformer, bool_cols),
    ],
)


# Define the final pipeline
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
])

# Apply the transformation
X_transformed = pipeline.fit_transform(X)

# Display the transformed data
print(X_transformed)


[[-0.35720609  0.35674094  0.          0.          0.        ]
 [-0.66784328  0.3565915   0.          0.          0.        ]
 [-0.36915368  0.41640683  0.          0.          0.        ]
 ...
 [ 0.14459244  0.4108474   0.          1.          0.        ]
 [ 0.24017311 -2.59117998  1.          1.          1.        ]
 [ 0.24017311 -2.59117998  1.          1.          1.        ]]


In [40]:
y_labeled = pd.get_dummies(y, drop_first=True)
y_labeled

Performance  Strictly Necessary  Targeting/Advertising
1             True               False                  False
2             True               False                  False
3             True               False                  False
5            False               False                   True
6             True               False                  False
...            ...                 ...                    ...
65262        False                True                  False
65273        False                True                  False
65282        False                True                  False
65286        False                True                  False
65288        False                True                  False

[32387 rows x 3 columns]

In [41]:
X_transformed.shape

(32387, 5)

In [42]:
y_labeled.shape

(32387, 3)

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X_transformed, y_labeled, random_state = 42, test_size = 0.2)


In [44]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(25909, 5)
(6478, 5)
(25909, 3)
(6478, 3)


In [45]:
# APPLYING Random Forest Classifier to the dataset where there is duplicated values. Empty category is removed.

In [46]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [47]:
y_predict = rf.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score

# Assuming y_test and y_predict are the true labels and predicted labels, respectively
accuracy = accuracy_score(y_test, y_predict)

print(f'Accuracy: {accuracy:.2%}')

Accuracy: 92.87%


In [49]:
!pip install xgboost

In [50]:
import xgboost as xgb

In [51]:
ab = xgb.XGBClassifier()
ab.fit(X_train, y_train)
y_predict = ab.predict(X_test)
accuracy = accuracy_score(y_test, y_predict)
print(f'Accuracy: {accuracy:.2%}')

Accuracy: 91.90%


In [52]:
# DF with no duplicate rows

In [53]:
df_no_dup = df.drop_duplicates()

In [54]:
len(df_no_dup)

30232

In [55]:
X_no_dup = df_no_dup.drop("category", axis = 1)
y_no_dup = df_no_dup.category

In [56]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np


# Separate columns for transformation and remaining columns
# text_cols = ['name', 'value', 'desc']
numeric_cols = ['size', 'expires']
bool_cols = ['httpOnly', 'secure', 'session']

# Define transformers
text_transformer = TfidfVectorizer()
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),  # Handle missing values if any
    ('scaler', StandardScaler())
])
bool_transformer = 'passthrough'  # No transformation needed for boolean columns

# Apply transformers to the specified columns
preprocessor = ColumnTransformer(
    transformers=[
#         ('text', text_transformer, text_cols),
#         ('category', category_transformer, category_cols),
        ('numeric', numeric_transformer, numeric_cols),
        ('bool', bool_transformer, bool_cols),
    ],
)


# Define the final pipeline
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
])

# Apply the transformation
X_transformed = pipeline.fit_transform(X)

# Display the transformed data
print(X_transformed)


[[-0.35720609  0.35674094  0.          0.          0.        ]
 [-0.66784328  0.3565915   0.          0.          0.        ]
 [-0.36915368  0.41640683  0.          0.          0.        ]
 ...
 [ 0.14459244  0.4108474   0.          1.          0.        ]
 [ 0.24017311 -2.59117998  1.          1.          1.        ]
 [ 0.24017311 -2.59117998  1.          1.          1.        ]]


In [57]:
y_labeled = pd.get_dummies(y, drop_first=True)

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X_transformed, y_labeled, random_state = 42, test_size = 0.2)

In [59]:
# Applying Random Forest to the dataset where there are no any duplicate rows

In [60]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [61]:

y_predict = rf.predict(X_test)

In [62]:
from sklearn.metrics import accuracy_score

# Assuming y_test and y_predict are the true labels and predicted labels, respectively
accuracy = accuracy_score(y_test, y_predict)

print(f'Accuracy: {accuracy:.2%}')

Accuracy: 92.82%


In [63]:
# Accuracy of randomforest is 91.90% if there are no duplicates.

In [64]:
# Hyperparameter tuning when only duplicate rows are removed

In [65]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

from sklearn.model_selection import GridSearchCV
parameters = [{
    'n_estimators': [50, 100, 200],          # Number of trees in the forest
    'max_depth': [None, 10, 20, 30],         # Maximum depth of the tree
    'min_samples_split': [2, 5, 10],         # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4]            # Minimum number of samples required to be at a leaf node
}]
grid_search = GridSearchCV(estimator=rf, 
                           param_grid=parameters, 
                           cv=5, 
                           scoring='accuracy')

grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid=[{'max_depth': [None, 10, 20, 30],
                          'min_samples_leaf': [1, 2, 4],
                          'min_samples_split': [2, 5, 10],
                          'n_estimators': [50, 100, 200]}],
             scoring='accuracy')

In [66]:
accuracy = grid_search.best_score_

In [67]:
accuracy

0.9263191793248063

In [68]:
grid_search.best_params_

{'max_depth': 20,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 50}

In [108]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth = 20, min_samples_leaf = 1, min_samples_split=2,n_estimators =100 )
rf.fit(X_train, y_train)
y_predict = rf.predict(X_test)

In [109]:
from sklearn.metrics import accuracy_score

# Assuming y_test and y_predict are the true labels and predicted labels, respectively
accuracy = accuracy_score(y_test, y_predict)

print(f'Accuracy: {accuracy:.2%}')    # This is the accuracy after hyper parameter tuning in random forest where dataset has no duplicate rows and names.

Accuracy: 93.28%
